---

- name: Install Jenkins and its prerequisites
  hosts: 127.0.0.1
  connection: local
  ansible_become: yes
  tasks:
#en el paso command con sh -c antes habia un sudo que saco por el sudo:yes
    - name: Install jdk8 (Jenkins prerequisite)
      apt:
        name: openjdk-8-jdk

    - name: Verify java version
      command: java -version 
      register: java_version

    - name: Add and enable Jenkins repository
      command: wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
      command: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

    - name: Update apt and install Jenkins
      apt:
        name: jenkins
        update_cache: yes

    - name: Open 8080(Jenkins default) port in firewall and start Jenkins service 
      command: ufw allow 8080 && service jenkins start

    - name: Verify firewall rules
      command: ufw status
      register: firewall_rules

    - name: Get Jenkins initial admin password(required for initial config)
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: initial_admin_password

    - debug: javaVersion=java_version.stdout_lines

    - debug: firewallRules=firewall_rules.stdout_lines

    - debug: initialAdminPassword=initial_admin_password.stdout_lines