---

- name: Install Firefox and gecko required for execution of Selenium tests
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
#this is supposed to be ran like this:
#ansible-playbook installFirefoxAndDriver.yml --ask-sudo-pass
    - name: Install Firefox
      apt:
        name: firefox

    - name: Change location to the one required by the script and download the driver there
      shell: curl -L https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz | tar zx
      args:
        chdir: /home/juanpa/drivers/