---
- name: Install Jenkins and its prerequisites
  hosts: 127.0.0.1
  connection: local
  sudo: yes
  tasks:

    - name: Install jdk8 (Jenkins prerequisite)
      apt:
        name: openjdk-8-jdk
      
    - name: Verify java version
      command: java -version 
      register: java_version


